### ISSUE TITLE
Week 6 content uploaded

### ISSUE THREAD

**Issue by edodson-matc** [madisoncollege-it-programs/python-scripting-edodson-matc#5]
realized i forgot to upload the week 6 content last week, so here it is

**Comment by cethenmc** [comment]
You took the liberty of changing the "and" to an "&", and though coincidentally they render the same result, they are not the same operator.

and is truly a Logical and whereas & is a bitwise operator.

The logical does a lazy evaluation, meaning it moves to the second term only if the first is true.

The ampersand evaluates as a binary.  Since True is 0001 it will evaluate to 1s as a 1, and in number 2 it will evaluate 0001 and 0000.  Remember how it compares each digit of the binary.

Therefore, I will record a 7.2 of 8  for your score.  Please reply to this open Issue ticket whether you'd like to correct numbers 1, 2, and 3 and resubmit, or just take the 7 out of 8.

**Comment by cethenmc** [comment]
Oops.  Forgot to mention flowcontrol.py receives full credit.

**Comment by edodson-matc** [comment]
Just fixed this, thanks for letting me know

**Comment by cethenmc** [comment]
> Just fixed this, thanks for letting me know

Thanks for making the change!  Switch grade to 8 of 8.

Please get Dictionaries and Functions labs in soon!
