### ISSUE TITLE
Week 9 ready for grading

### ISSUE THREAD

**Issue by edodson-matc** [madisoncollege-it-programs/python-scripting-edodson-matc#9]

**Comment by cethenmc** [comment]
Neither script is set to execute from the command line. Please be courteous to do it in the future.

Secondly, it is best practice to define the main() function instead of just adding the print in the if logic.  I will mark you down as **7 of 8 for now**, as the directions explicitly call for it:  "Create a main function that calls the convert_temp() function with an argument of 32."  Please resubmit for full credit.

I will also add that if the tempconversion.py was intended to be run through the "main()" function:  "Script 2 - Temp Conversion (**Main**)."  You may consider modifying your tempconversion.py script or creating another (tempconversion2.py) where it will use __name__ to ensure the main() function runs.  Your main function can be the code you made in tempconversion.py.

**Comment by cethenmc** [comment]
Thanks for modifying.  8 of 8 now!
